export const PICTURE_VISIBLE_INTERVAL = 300
export const PICTURE_INNER_PADDING = 5
export const PICTURE_LABEL_LINE_HEIGHT = 18
export const PICTURE_LABEL_MARGIN_TOP = 6
export const PICTURE_LABEL_MARGIN_BOTTOM = 2
